# Generated by Django 4.1.2 on 2022-12-09 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_account',
            fields=[
                ('name', models.CharField(max_length=25)),
                ('add', models.TextField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=25)),
                ('phno', models.BigIntegerField()),
                ('dob', models.DateField()),
                ('ration', models.BigIntegerField()),
                ('pancard', models.CharField(max_length=25)),
                ('adhar_no', models.BigIntegerField()),
                ('ifsc_code', models.CharField(max_length=20)),
                ('account_number', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nominee_acc_no', models.BigIntegerField()),
                ('balance', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('post_box_number', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Letter_Percel',
            fields=[
                ('category', models.CharField(choices=[('L', 'Letter'), ('P', 'Parcel')], max_length=20)),
                ('sname', models.CharField(max_length=25)),
                ('s_add', models.TextField(max_length=100)),
                ('s_pin', models.IntegerField()),
                ('s_state', models.CharField(max_length=25)),
                ('s_phon', models.BigIntegerField()),
                ('s_city', models.CharField(max_length=25)),
                ('rname', models.CharField(max_length=25)),
                ('r_add', models.TextField(max_length=100)),
                ('r_pin', models.IntegerField()),
                ('r_state', models.CharField(max_length=25)),
                ('r_phon', models.BigIntegerField()),
                ('r_city', models.CharField(max_length=25)),
                ('weight', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pbno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postoffice.admin')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='postoffice.letter_percel')),
                ('status', models.CharField(choices=[('D', 'Delivered'), ('N', 'Not delivered')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('date', models.DateField()),
                ('amount', models.IntegerField()),
                ('account_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postoffice.add_account')),
            ],
        ),
        migrations.CreateModel(
            name='MoneyOrder',
            fields=[
                ('sname', models.CharField(max_length=25)),
                ('s_add', models.TextField(max_length=100)),
                ('s_pin', models.IntegerField()),
                ('s_state', models.CharField(max_length=25)),
                ('s_phon', models.BigIntegerField()),
                ('s_city', models.CharField(max_length=25)),
                ('rname', models.CharField(max_length=25)),
                ('r_add', models.TextField(max_length=100)),
                ('r_pin', models.IntegerField()),
                ('r_state', models.CharField(max_length=25)),
                ('r_phon', models.BigIntegerField()),
                ('r_city', models.CharField(max_length=25)),
                ('t_amount', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('m_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pbno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postoffice.admin')),
            ],
        ),
        migrations.CreateModel(
            name='E_bill',
            fields=[
                ('b_id', models.IntegerField()),
                ('b_name', models.CharField(max_length=25)),
                ('b_address', models.TextField()),
                ('l_usedunit', models.IntegerField()),
                ('c_unit', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('c_date', models.DateField()),
                ('recipt_no', models.IntegerField(primary_key=True, serialize=False)),
                ('account_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postoffice.add_account')),
            ],
        ),
        migrations.CreateModel(
            name='CreateInsurance',
            fields=[
                ('insurance_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=20)),
                ('amount', models.IntegerField()),
                ('pancard', models.CharField(max_length=25)),
                ('age', models.IntegerField()),
                ('account_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postoffice.add_account')),
            ],
        ),
        migrations.CreateModel(
            name='claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('amount', models.IntegerField()),
                ('insurance_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postoffice.createinsurance')),
            ],
        ),
        migrations.CreateModel(
            name='Add_money',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('amount', models.IntegerField()),
                ('account_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postoffice.add_account')),
            ],
        ),
        migrations.AddField(
            model_name='add_account',
            name='pbno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postoffice.admin'),
        ),
    ]
