# Generated by Django 4.1.2 on 2022-12-09 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postoffice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_account',
            name='ration',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
